# 手動載入 React Native 腳本，跳過版本檢查
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '15.1'

# 跳過版本檢查
def prepare_react_native_project!
  # 自定義版本，跳過 Xcode 版本檢查
  # 不執行任何版本檢查
end

prepare_react_native_project!

# 手動設定環境變數來繞過版本檢查
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_FRAMEWORKS'] = 'static'
ENV['RCT_FABRIC_ENABLED'] = '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PetProject' do
  config = use_native_modules!
  
  # Google Maps SDK for react-native-maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Google-Maps-iOS-Utils'
  
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :fabric_enabled => false,
    :hermes_enabled => false
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # 添加 HAVE_GOOGLE_MAPS 宏定義
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'HAVE_GOOGLE_MAPS=1'
      end
    end
    
    # 為主專案也添加 HAVE_GOOGLE_MAPS 宏定義
    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
        xcconfig_path = target.xcconfig_path(variant)
        xcconfig_content = File.read(xcconfig_path)
        unless xcconfig_content.include?('HAVE_GOOGLE_MAPS=1')
          xcconfig_content += "\nGCC_PREPROCESSOR_DEFINITIONS = $(inherited) HAVE_GOOGLE_MAPS=1\n"
          File.write(xcconfig_path, xcconfig_content)
        end
      end
    end
  end
end
