// src/constants/mockData.native.ts

export const mockHotels = [
  {
    id: 1,
    imageUrl: require('../../assets/mockData/001.webp'),
    title: '測試旅館 1 號',
    distance: '381m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 2,
    imageUrl: require('../../assets/mockData/002.webp'),
    title: '測試旅館 2 號',
    distance: '382m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 3,
    imageUrl: require('../../assets/mockData/003.webp'),
    title: '測試旅館 3 號',
    distance: '383m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 4,
    imageUrl: require('../../assets/mockData/004.webp'),
    title: '測試旅館 4 號',
    distance: '384m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 5,
    imageUrl: require('../../assets/mockData/005.webp'),
    title: '測試旅館 5 號',
    distance: '385m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 6,
    imageUrl: require('../../assets/mockData/006.webp'),
    title: '測試旅館 6 號',
    distance: '386m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 7,
    imageUrl: require('../../assets/mockData/007.webp'),
    title: '測試旅館 7 號',
    distance: '387m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 8,
    imageUrl: require('../../assets/mockData/008.webp'),
    title: '測試旅館 8 號',
    distance: '388m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 9,
    imageUrl: require('../../assets/mockData/009.webp'),
    title: '測試旅館 9 號',
    distance: '389m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 10,
    imageUrl: require('../../assets/mockData/010.webp'),
    title: '測試旅館 10 號',
    distance: '390m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 11,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 11 號',
    distance: '391m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 12,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 12 號',
    distance: '392m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 13,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 13 號',
    distance: '393m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 14,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 14 號',
    distance: '394m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 15,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 15 號',
    distance: '395m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 16,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 16 號',
    distance: '396m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 17,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 17 號',
    distance: '397m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 18,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 18 號',
    distance: '398m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 19,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 19 號',
    distance: '399m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 20,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 20 號',
    distance: '400m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 21,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 21 號',
    distance: '401m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 22,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 22 號',
    distance: '402m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 23,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 23 號',
    distance: '403m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 24,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 24 號',
    distance: '404m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 25,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 25 號',
    distance: '405m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 26,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 26 號',
    distance: '406m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 27,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 27 號',
    distance: '407m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 28,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 28 號',
    distance: '408m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 29,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 29 號',
    distance: '409m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 30,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 30 號',
    distance: '410m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 31,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 31 號',
    distance: '411m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 32,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 32 號',
    distance: '412m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 33,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 33 號',
    distance: '413m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 34,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 34 號',
    distance: '414m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 35,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 35 號',
    distance: '415m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 36,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 36 號',
    distance: '416m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 37,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 37 號',
    distance: '417m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 38,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 38 號',
    distance: '418m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 39,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 39 號',
    distance: '419m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 40,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 40 號',
    distance: '420m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 41,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 41 號',
    distance: '421m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 42,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 42 號',
    distance: '422m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 43,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 43 號',
    distance: '423m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 44,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 44 號',
    distance: '424m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 45,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 45 號',
    distance: '425m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 46,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 46 號',
    distance: '426m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 47,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 47 號',
    distance: '427m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 48,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 48 號',
    distance: '428m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 49,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 49 號',
    distance: '429m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 50,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 50 號',
    distance: '380m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 51,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 51 號',
    distance: '381m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 52,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 52 號',
    distance: '382m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 53,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 53 號',
    distance: '383m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 54,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 54 號',
    distance: '384m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 55,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 55 號',
    distance: '385m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 56,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 56 號',
    distance: '386m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 57,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 57 號',
    distance: '387m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 58,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 58 號',
    distance: '388m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 59,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 59 號',
    distance: '389m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 60,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 60 號',
    distance: '390m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 61,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 61 號',
    distance: '391m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 62,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 62 號',
    distance: '392m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 63,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 63 號',
    distance: '393m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 64,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 64 號',
    distance: '394m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 65,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 65 號',
    distance: '395m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 66,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 66 號',
    distance: '396m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 67,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 67 號',
    distance: '397m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 68,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 68 號',
    distance: '398m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 69,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 69 號',
    distance: '399m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 70,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 70 號',
    distance: '400m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 71,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 71 號',
    distance: '401m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 72,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 72 號',
    distance: '402m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 73,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 73 號',
    distance: '403m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 74,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 74 號',
    distance: '404m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 75,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 75 號',
    distance: '405m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 76,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 76 號',
    distance: '406m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 77,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 77 號',
    distance: '407m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 78,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 78 號',
    distance: '408m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 79,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 79 號',
    distance: '409m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 80,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 80 號',
    distance: '410m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 81,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 81 號',
    distance: '411m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 82,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 82 號',
    distance: '412m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 83,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 83 號',
    distance: '413m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 84,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 84 號',
    distance: '414m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 85,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 85 號',
    distance: '415m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 86,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 86 號',
    distance: '416m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 87,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 87 號',
    distance: '417m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 88,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 88 號',
    distance: '418m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 89,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 89 號',
    distance: '419m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 90,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 90 號',
    distance: '420m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 91,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 91 號',
    distance: '421m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 92,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 92 號',
    distance: '422m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 93,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 93 號',
    distance: '423m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 94,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 94 號',
    distance: '424m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 95,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 95 號',
    distance: '425m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 96,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 96 號',
    distance: '426m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 97,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 97 號',
    distance: '427m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  },
  {
    id: 98,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 98 號',
    distance: '428m',
    rating: 3,
    likes: 4.0,
    price: 'TWD 4,000',
  },
  {
    id: 99,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 99 號',
    distance: '429m',
    rating: 5,
    likes: 5.0,
    price: 'TWD 4,000',
  },
  {
    id: 100,
    imageUrl: require('../../assets/error.png'),
    title: '測試旅館 100 號',
    distance: '380m',
    rating: 4,
    likes: 4.5,
    price: 'TWD 4,000',
  }
];

export default mockHotels;